# Generated by Django 2.2.8 on 2021-04-17 11:44

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('runs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('strike_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('players', django_mysql.models.ListCharField(models.CharField(max_length=15), default=[], max_length=200, size=11)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('place', models.CharField(blank=True, default='', max_length=100)),
                ('teams', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='Upcoming', max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('winner', django_mysql.models.ListCharField(models.CharField(max_length=15), default=[], max_length=100, size=5)),
                ('loser', django_mysql.models.ListCharField(models.CharField(max_length=15), default=[], max_length=100, size=5)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tournament')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField(blank=True, null=True)),
                ('over', models.PositiveIntegerField(blank=True, null=True)),
                ('run', models.PositiveIntegerField(blank=True, null=True)),
                ('ball', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('batsman', models.CharField(blank=True, max_length=100)),
                ('bowler', models.CharField(blank=True, max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('overs', models.FloatField(default=0)),
                ('runs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('maidens', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('no_balls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('wides', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('wickets', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('economy', models.CharField(blank=True, default='', max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('runs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('balls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sixes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('strike_rate', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('last_info', django_mysql.models.ListCharField(models.CharField(max_length=15), default=[], max_length=50, size=2)),
                ('pos', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
            options={
                'verbose_name_plural': 'Batsmen',
            },
        ),
    ]
