# Generated by Django 2.2.8 on 2021-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
