# Generated by Django 2.2.8 on 2021-04-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_match_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='uniqueid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
