# Generated by Django 2.2.8 on 2021-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210426_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
