# Generated by Django 2.2.8 on 2021-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210426_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
