# Generated by Django 2.2.8 on 2021-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tournament_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
