# Generated by Django 2.2.8 on 2021-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210712_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='report',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
