# Generated by Django 2.2.8 on 2021-07-13 14:13

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_match_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=[], max_length=310, size=6),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=[], max_length=310, size=6),
        ),
    ]
