# Generated by Django 2.2.8 on 2021-07-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_commentator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentator',
        ),
    ]
