# Generated by Django 2.2.8 on 2021-07-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_commentator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
