# Generated by Django 2.2.8 on 2021-08-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_trigger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
