# Generated by Django 3.2.4 on 2021-08-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='uniqueid',
        ),
    ]
