# Generated by Django 3.2.4 on 2021-08-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_match_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='uniqueid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
