# Generated by Django 3.2.4 on 2021-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='team2id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
