# Generated by Django 3.2.4 on 2021-09-01 07:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210818_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2id',
        ),
        migrations.AddField(
            model_name='profiles',
            name='field_name',
            field=models.FileField(default='', max_length=254, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=[], max_length=5000, size=8),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=[], max_length=5000, size=8),
        ),
    ]
