# Generated by Django 3.2.4 on 2021-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_team_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csv')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
