# Generated by Django 3.2.4 on 2021-09-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210907_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='field_name',
        ),
    ]
