# Generated by Django 3.2.4 on 2021-09-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_profiles_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='file_name',
            field=models.FileField(upload_to='', verbose_name=''),
        ),
    ]
