# Generated by Django 3.2.4 on 2021-09-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_txt_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
            preserve_default=False,
        ),
    ]
