# Generated by Django 3.2.4 on 2021-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
