# Generated by Django 3.2.4 on 2021-09-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210914_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='pointstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(blank=True, default='', max_length=100)),
                ('win', models.CharField(blank=True, default='', max_length=100)),
                ('lose', models.CharField(blank=True, default='', max_length=100)),
                ('draw', models.CharField(blank=True, default='', max_length=100)),
                ('tournament', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tournament')),
            ],
        ),
    ]
