# Generated by Django 3.2.4 on 2021-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_pointstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='lose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
