# Generated by Django 2.2.8 on 2021-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20211031_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='draw',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='lose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
