# Generated by Django 2.2.8 on 2021-11-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20211102_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstable',
            name='tournament',
        ),
    ]
