# Generated by Django 2.2.8 on 2021-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20211102_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstable',
            name='draw',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='lose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
