# Generated by Django 2.2.8 on 2021-11-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20211102_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstable',
            name='teams',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
