# Generated by Django 2.2.8 on 2021-11-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_pointstable_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstable',
            name='tournament',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tournament'),
        ),
    ]
