# Generated by Django 3.2.4 on 2021-11-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='lose',
        ),
    ]
