# Generated by Django 3.2.4 on 2021-11-04 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0049_auto_20211104_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tournament', to='app.tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
