# Generated by Django 3.2.4 on 2021-11-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20211104_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='win',
        ),
    ]
