# Generated by Django 3.1.6 on 2021-11-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0051_remove_tournament_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentator',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commentator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Commentator', to=settings.AUTH_USER_MODEL),
        ),
    ]
