# Generated by Django 2.2.8 on 2021-11-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20211111_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tournament', to=settings.AUTH_USER_MODEL),
        ),
    ]
