# Generated by Django 2.2.8 on 2022-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20211120_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
