# Generated by Django 2.2.8 on 2022-01-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20220106_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
